## Settings
title: "ASTRON LAGRANGE'S HOMEPAGE"
owner: "ASTRON"
url: "https://astroneko404.github.io/"
baseurl: ""
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
github: "Astroneko404"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets"
statement: "DESIGNED BY DEERRIDER, ALL RIGHTS RESERVED"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
